SYMBOL_UNIVERSE = [
    "BTCUSDT",
    "ETHUSDT",
    "SOLUSDT",
    "BNBUSDT",
    "XRPUSDT",
    "ADAUSDT",
    "DOGEUSDT",
    "LINKUSDT",
    "AVAXUSDT",
    "MATICUSDT",
    "DOTUSDT",
    "LTCUSDT",
    "BCHUSDT",
    "TRXUSDT",
    "ATOMUSDT",
    "ETCUSDT",
    "NEARUSDT",
    "APTUSDT",
    "ARBUSDT",
    "OPUSDT",
]

ENABLE_DYNAMIC_SYMBOL_UNIVERSE = True
DYNAMIC_UNIVERSE_LIMIT = 10
DYNAMIC_UNIVERSE_CACHE_SEC = 300
DYNAMIC_UNIVERSE_QUOTE_ASSET = "USDT"
DYNAMIC_UNIVERSE_MIN_QUOTE_VOLUME = 0.0

SCAN_INTERVAL_SEC = 5
MAX_OPEN_POSITION = 3
MAX_SYMBOL_ACTIVE = 3
SHORT_BIAS_GUARD_ENABLED = True
MAX_SHORT_POSITIONS = 8
MIN_LONG_RATIO = 0.10
BIAS_CHECK_WINDOW = 20
MAX_PORTFOLIO_EXPOSURE = 0.30
MAX_SIDE_EXPOSURE = 0.20
MIN_ENTRY_QUALITY_SCORE = 0.10
DRAWDDOWN_SOFT_LIMIT = 0.05
WIN_RATE_SOFT_LIMIT = 0.45
MAX_ACCOUNT_DRAWDOWN = 0.10
MAX_CONSECUTIVE_LOSS = 3
MAX_VOLATILITY_THRESHOLD = 0.08
API_FAILURE_LIMIT = 3
ENGINE_ERROR_LIMIT = 3
ENABLE_MARKET_REGIME = True
REGIME_TREND_THRESHOLD = 0.002
REGIME_VOL_HIGH = 0.03
REGIME_VOL_LOW = 0.01
ENABLE_PORTFOLIO_ALLOCATION = True
ALLOCATION_MAX_WEIGHT = 0.40
ALLOCATION_MIN_WEIGHT = 0.05
ALLOCATION_OBSERVATION_MODE = False

# Gemini Policy Patch (PHASE5.7)
MIN_EDGE_THRESHOLD = 0.05
EDGE_SCORE_THRESHOLD = MIN_EDGE_THRESHOLD
HIGH_VOL_POLICY = "REDUCED_SIZE"

